In [1]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
from pathlib import Path

PAPERS_DIR = Path(
    "/content/drive/MyDrive/Colab Notebooks/Project/Data/papers"
)

if not PAPERS_DIR.exists():
    raise FileNotFoundError(
        f"Folder not found: {PAPERS_DIR}"
    )

pdf_files = sorted(PAPERS_DIR.glob("*.pdf"))

print(f"Found {len(pdf_files)} PDF files:")

for path in pdf_files:
    print(f"- {path.name}")

Found 5 PDF files:
- Attention.pdf
- BERT.pdf
- NMT.pdf
- ODQA.pdf
- RAG.pdf

In [3]:
!pip install pymupdf

Collecting pymupdf
  Downloading pymupdf-1.28.2-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (26 kB)
Downloading pymupdf-1.28.2-cp310-abi3-manylinux_2_28_x86_64.whl (25.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 44.0 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.28.2

In [4]:
import pymupdf
import pandas as pd

documents = []

for paper_id, pdf_path in enumerate(pdf_files, start=1):

    with pymupdf.open(pdf_path) as pdf:

        metadata = pdf.metadata or {}
        title = metadata.get("title") or pdf_path.stem

        print(f"Processing: {pdf_path.name}")

        for page_index, page in enumerate(pdf):

            text = page.get_text("text").strip()

            if not text:
                continue

            documents.append({
                "paper_id": paper_id,
                "title": title,
                "source": pdf_path.name,
                "page": page_index + 1,
                "text": text
            })

df = pd.DataFrame(documents)

print("\nExtraction complete")
print("Papers:", df["paper_id"].nunique())
print("Pages extracted:", len(df))
print("Total characters:", df["text"].str.len().sum())

display(df.head(3))

Processing: Attention.pdf
Processing: BERT.pdf
Processing: NMT.pdf
Processing: ODQA.pdf
Processing: RAG.pdf

Extraction complete
Papers: 5
Pages extracted: 73
Total characters: 258848

,paper_id,title,source,page,text
0,1,Attention,Attention.pdf,1,"Provided proper attribution is provided, Googl..."
1,1,Attention,Attention.pdf,2,"1\nIntroduction\nRecurrent neural networks, lo..."
2,1,Attention,Attention.pdf,3,Figure 1: The Transformer - model architecture...

In [5]:
import json

CORPUS_PATH = (
    "/content/drive/MyDrive/Colab Notebooks/Project/"
    "Data/research_corpus.jsonl"
)

with open(CORPUS_PATH, "w", encoding="utf-8") as f:
    for record in documents:
        f.write(
            json.dumps(record, ensure_ascii=False) + "\n"
        )

print("Corpus saved to:", CORPUS_PATH)

Corpus saved to: /content/drive/MyDrive/Colab Notebooks/Project/Data/research_corpus.jsonl

In [6]:

print("Papers:", df["paper_id"].nunique())
print("Pages:", len(df))
display(df[["title", "source", "page", "text"]].head(3))

Papers: 5
Pages: 73

,title,source,page,text
0,Attention,Attention.pdf,1,"Provided proper attribution is provided, Googl..."
1,Attention,Attention.pdf,2,"1\nIntroduction\nRecurrent neural networks, lo..."
2,Attention,Attention.pdf,3,Figure 1: The Transformer - model architecture...

In [7]:
import re
import pandas as pd

CHUNK_SIZE = 180
CHUNK_OVERLAP = 40

def chunk_text(text, chunk_size=180, overlap=40):
    words = re.findall(r"\S+", text)

    if not words:
        return []

    chunks = []
    step = chunk_size - overlap

    for start in range(0, len(words), step):
        chunk_words = words[start:start + chunk_size]

        if not chunk_words:
            break

        chunks.append(" ".join(chunk_words))

        if start + chunk_size >= len(words):
            break

    return chunks


chunks = []

for row in documents:
    page_chunks = chunk_text(
        row["text"],
        chunk_size=CHUNK_SIZE,
        overlap=CHUNK_OVERLAP
    )

    for chunk_index, chunk in enumerate(page_chunks):
        chunks.append({
            "paper_id": row["paper_id"],
            "title": row["title"],
            "source": row["source"],
            "page": row["page"],
            "chunk_id": (
                f'{row["paper_id"]}_'
                f'{row["page"]}_'
                f'{chunk_index}'
            ),
            "text": chunk
        })

chunks_df = pd.DataFrame(chunks)

print("Pages:", len(documents))
print("Chunks:", len(chunks_df))
print("Average words per chunk:",
      round(chunks_df["text"].str.split().str.len().mean(), 1))

display(chunks_df.head(3))

Pages: 73
Chunks: 298
Average words per chunk: 163.4

,paper_id,title,source,page,chunk_id,text
0,1,Attention,Attention.pdf,1,1_1_0,"Provided proper attribution is provided, Googl..."
1,1,Attention,Attention.pdf,1,1_1_1,quality while being more parallelizable and re...
2,1,Attention,Attention.pdf,1,1_1_2,of this work. Noam proposed scaled dot-product...

In [8]:
sample = chunks_df.iloc[0]

print("Chunk ID:", sample["chunk_id"])
print("Source:", sample["source"])
print("Page:", sample["page"])
print("-" * 80)
print(sample["text"])

Chunk ID: 1_1_0
Source: Attention.pdf
Page: 1
--------------------------------------------------------------------------------
Provided proper attribution is provided, Google hereby grants permission to reproduce the tables and figures in this paper solely for use in journalistic or scholarly works. Attention Is All You Need Ashish Vaswani∗ Google Brain avaswani@google.com Noam Shazeer∗ Google Brain noam@google.com Niki Parmar∗ Google Research nikip@google.com Jakob Uszkoreit∗ Google Research usz@google.com Llion Jones∗ Google Research llion@google.com Aidan N. Gomez∗† University of Toronto aidan@cs.toronto.edu Łukasz Kaiser∗ Google Brain lukaszkaiser@google.com Illia Polosukhin∗‡ illia.polosukhin@gmail.com Abstract The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English- to-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT

In [9]:
import json

CHUNKS_PATH = (
    "/content/drive/MyDrive/Colab Notebooks/Project/"
    "Data/chunks.jsonl"
)

with open(CHUNKS_PATH, "w", encoding="utf-8") as f:
    for record in chunks:
        f.write(
            json.dumps(record, ensure_ascii=False) + "\n"
        )

print("Saved chunks to:", CHUNKS_PATH)

Saved chunks to: /content/drive/MyDrive/Colab Notebooks/Project/Data/chunks.jsonl

In [10]:
from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer("all-MiniLM-L6-v2")

chunk_texts = chunks_df["text"].tolist()

chunk_embeddings = model.encode(
    chunk_texts,
    batch_size=16,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Number of chunks:", len(chunk_texts))
print("Embedding matrix shape:", chunk_embeddings.shape)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Number of chunks: 298
Embedding matrix shape: (298, 384)

In [11]:
def retrieve(query, top_k=5):
  query_embedding = model.encode(
      [query],
      convert_to_numpy=True,
      normalize_embeddings=True
  )[0]

  scores = chunk_embeddings @ query_embedding

  top_indices = np.argsort(scores)[::-1][:top_k]

  results = chunks_df.iloc[top_indices].copy()
  results["similarity"] = scores[top_indices]

  return results

In [12]:
query = "Why does the Transformer use attention instead of recurrence?"

results = retrieve(query, top_k=5)

for _, row in results.iterrows():
    print(f'\nSource: {row["source"]}')
    print(f'Page: {row["page"]}')
    print(f'Chunk: {row["chunk_id"]}')
    print(f'Similarity: {row["similarity"]:.4f}')
    print(row["text"][:700])
    print("-" * 80)

Source: Attention.pdf
Page: 5
Chunk: 1_5_1
Similarity: 0.5638
Applications of Attention in our Model The Transformer uses multi-head attention in three different ways: • In "encoder-decoder attention" layers, the queries come from the previous decoder layer, and the memory keys and values come from the output of the encoder. This allows every position in the decoder to attend over all positions in the input sequence. This mimics the typical encoder-decoder attention mechanisms in sequence-to-sequence models such as [38, 2, 9]. • The encoder contains self-attention layers. In a self-attention layer all of the keys, values and queries come from the same place, in this case, the output of the previous layer in the encoder. Each position in the encoder can
--------------------------------------------------------------------------------

Source: Attention.pdf
Page: 2
Chunk: 1_2_1
Similarity: 0.5313
through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc- tion models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw glo
--------------------------------------------------------------------------------

Source: Attention.pdf
Page: 2
Chunk: 1_2_3
Similarity: 0.4921
in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations [4, 27, 28, 22]. End-to-end memory networks are based on a recurrent attention mechanism instead of sequence- aligned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [34]. To the best of our knowledge, however, the Transformer is the first transduction model relying entirely on self-attention to compute representations of its input and output without using sequence- aligned RNNs o
--------------------------------------------------------------------------------

Source: Attention.pdf
Page: 3
Chunk: 1_3_0
Similarity: 0.4628
Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively. 3.1 Encoder and Decoder Stacks Encoder: The encoder is composed of a stack of N = 6 identical layers. Each layer has two sub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, position- wise fully connected feed-forward network. We employ a residual connection [11] around each of the two sub-layers, followed by layer normalization [1]. That is, the output of each sub-layer is LayerNorm(x + Sublayer
--------------------------------------------------------------------------------

Source: Attention.pdf
Page: 6
Chunk: 1_6_2
Similarity: 0.4580
nearly identical results (see Table 3 row (E)). We chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than the ones encountered during training. 4 Why Self-Attention In this section we compare various aspects of self-attention layers to the recurrent and convolu- tional layers commonly used for mapping one variable-length sequence of symbol representations (x1, ..., xn) to another sequence of equal length (z1, ..., zn), with xi, zi ∈Rd, such as a hidden layer in a typical sequence transduction encoder or decoder. Motivating our use of self-attention we consider three desiderata. One is the total computational complexity per layer. Another is
--------------------------------------------------------------------------------

In [13]:
results = retrieve(
    "How does scaled dot-product attention calculate attention weights?",
    top_k=5
)

display(
    results[["source", "page", "chunk_id", "similarity"]]
)

           source  page chunk_id  similarity
10  Attention.pdf     4    1_4_0    0.656104
11  Attention.pdf     4    1_4_1    0.619635
12  Attention.pdf     4    1_4_2    0.598767
2   Attention.pdf     1    1_1_2    0.535249
14  Attention.pdf     5    1_5_1    0.423789

In [14]:
eval_questions = [
    "Why does the Transformer eliminate recurrence?",
    "How does scaled dot-product attention work?",
    "What is the purpose of multi-head attention?",
    "How does Bahdanau attention calculate alignment scores?",
    "What is the difference between sparse and dense retrieval?",
    "How does Retrieval-Augmented Generation combine retrieval and generation?",
    "How does Dense Passage Retrieval represent questions and passages?",
    "Why are sentence embeddings useful for semantic search?",
    "What is the role of positional encoding in Transformers?",
    "How can a RAG system determine whether a claim is supported by evidence?"
]

In [15]:
for i, query in enumerate(eval_questions, start=1):
    print(f"\n{'=' * 90}")
    print(f"Q{i}: {query}")

    results = retrieve(query, top_k=3)

    for rank, (_, row) in enumerate(results.iterrows(), start=1):
        print(
            f"\nRank: {rank} | "
            f"Chunk: {row['chunk_id']} | "
            f"Page: {row['page']} | "
            f"Score: {row['similarity']:.3f}"
        )
        print(row["text"][:350])

==========================================================================================
Q1: Why does the Transformer eliminate recurrence?

Rank: 1 | Chunk: 1_2_1 | Page: 2 | Score: 0.346
through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc- tion models in various tasks, allowing modeling of d

Rank: 2 | Chunk: 1_5_1 | Page: 5 | Score: 0.338
Applications of Attention in our Model The Transformer uses multi-head attention in three different ways: • In "encoder-decoder attention" layers, the queries come from the previous decoder layer, and the memory keys and values come from the output of the encoder. This allows every position in the decoder to attend over all positions in the input s

Rank: 3 | Chunk: 1_3_0 | Page: 3 | Score: 0.297
Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively. 3.1 Encoder and Decoder Stacks Encoder: The encoder is composed of a stack of N = 6 iden

==========================================================================================
Q2: How does scaled dot-product attention work?

Rank: 1 | Chunk: 1_4_2 | Page: 4 | Score: 0.667
counteract this effect, we scale the dot products by 1 √dk . 3.2.2 Multi-Head Attention Instead of performing a single attention function with dmodel-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to dk, dk and dv dimensions, respective

Rank: 2 | Chunk: 1_4_1 | Page: 4 | Score: 0.642
as: Attention(Q, K, V ) = softmax(QKT √dk )V (1) The two most commonly used attention functions are additive attention [2], and dot-product (multi- plicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √dk . Additive attention computes the compatibility function using a feed-forward network wi

Rank: 3 | Chunk: 1_4_0 | Page: 4 | Score: 0.617
Scaled Dot-Product Attention Multi-Head Attention Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel. of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key. 3.2.1 Scaled Dot-Product Atten

==========================================================================================
Q3: What is the purpose of multi-head attention?

Rank: 1 | Chunk: 1_5_0 | Page: 5 | Score: 0.561
output values. These are concatenated and once again projected, resulting in the final values, as depicted in Figure 2. Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions. With a single attention head, averaging inhibits this. MultiHead(Q, K, V ) = Concat(head1, ...,

Rank: 2 | Chunk: 1_13_0 | Page: 13 | Score: 0.460
Attention Visualizations It is in this spirit that a majority of American governments have passed new laws since 2009 making the registration or voting process more difficult . <EOS> <pad> <pad> <pad> <pad> <pad> <pad> It is in this spirit that a majority of American governments have passed new laws since 2009 making the registration or voting proc

Rank: 3 | Chunk: 1_4_2 | Page: 4 | Score: 0.453
counteract this effect, we scale the dot products by 1 √dk . 3.2.2 Multi-Head Attention Instead of performing a single attention function with dmodel-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to dk, dk and dv dimensions, respective

==========================================================================================
Q4: How does Bahdanau attention calculate alignment scores?

Rank: 1 | Chunk: 3_12_3 | Page: 12 | Score: 0.474
the output probabilities (one for each word) with a softmax function (see Eq. (6)). A.1.2 ALIGNMENT MODEL The alignment model should be designed considering that the model needs to be evaluated Tx × Ty times for each sentence pair of lengths Tx and Ty. In order to reduce computation, we use a single- layer multilayer perceptron such that a(si−1, hj

Rank: 2 | Chunk: 3_4_0 | Page: 4 | Score: 0.465
Published as a conference paper at ICLR 2015 the alignment is not considered to be a latent variable. Instead, the alignment model directly com- putes a soft alignment, which allows the gradient of the cost function to be backpropagated through. This gradient can be used to train the alignment model as well as the whole translation model jointly. W

Rank: 3 | Chunk: 3_3_3 | Page: 3 | Score: 0.420
The weight αij of each annotation hj is computed by αij = exp (eij) PTx k=1 exp (eik) , (6) where eij = a(si−1, hj) is an alignment model which scores how well the inputs around position j and the output at position i match. The score is based on the RNN hidden state si−1 (just before emitting yi, Eq. (4)) and the j-th annotation hj of the input se

==========================================================================================
Q5: What is the difference between sparse and dense retrieval?

Rank: 1 | Chunk: 4_2_4 | Page: 2 | Score: 0.524
et al., 2017).4 Formally speaking, a retriever R : (q, C) →CF is a function that takes as input a question q and a corpus C and returns a much smaller ﬁlter set of texts CF ⊂C, where |CF| = k ≪|C|. For a ﬁxed k, a retriever can be evaluated in isolation on top-k retrieval accuracy, which is the fraction of ques- tions for which CF contains a span t

Rank: 2 | Chunk: 4_1_2 | Page: 1 | Score: 0.464
been released at https://github.com/facebookresearch/DPR. 2For instance, the exact match score on SQuAD v1.1 drops from above 80% to less than 40% (Yang et al., 2019a). Retrieval in open-domain QA is usually imple- mented using TF-IDF or BM25 (Robertson and Zaragoza, 2009), which matches keywords efﬁ- ciently with an inverted index and can be seen

Rank: 3 | Chunk: 5_19_1 | Page: 19 | Score: 0.464
728 dimensional vectors, consisting of 15.3B values. These can be easily be stored at 8-bit ﬂoating point precision to manage memory and disk footprints. H Retrieval Collapse In preliminary experiments, we observed that for some tasks such as story generation [11], the retrieval component would “collapse” and learn to retrieve the same documents re

==========================================================================================
Q6: How does Retrieval-Augmented Generation combine retrieval and generation?

Rank: 1 | Chunk: 5_9_3 | Page: 9 | Score: 0.637
several differences, including less of emphasis on lightly editing a retrieved item, but on aggregating content from several pieces of retrieved content, as well as learning latent retrieval, and retrieving evidence documents rather than related training pairs. This said, RAG techniques may work well in these settings, and could represent promising

Rank: 2 | Chunk: 5_19_1 | Page: 19 | Score: 0.578
728 dimensional vectors, consisting of 15.3B values. These can be easily be stored at 8-bit ﬂoating point precision to manage memory and disk footprints. H Retrieval Collapse In preliminary experiments, we observed that for some tasks such as story generation [11], the retrieval component would “collapse” and learn to retrieve the same documents re

Rank: 3 | Chunk: 5_7_3 | Page: 7 | Score: 0.576
gold article is present in the top 10 retrieved articles in 90% of cases. 4.5 Additional Results Generation Diversity Section 4.3 shows that RAG models are more factual and speciﬁc than BART for Jeopardy question generation. Following recent work on diversity-promoting decoding [33, 59, 39], we also investigate generation diversity by calculating t

==========================================================================================
Q7: How does Dense Passage Retrieval represent questions and passages?

Rank: 1 | Chunk: 4_2_4 | Page: 2 | Score: 0.708
et al., 2017).4 Formally speaking, a retriever R : (q, C) →CF is a function that takes as input a question q and a corpus C and returns a much smaller ﬁlter set of texts CF ⊂C, where |CF| = k ≪|C|. For a ﬁxed k, a retriever can be evaluated in isolation on top-k retrieval accuracy, which is the fraction of ques- tions for which CF contains a span t

Rank: 2 | Chunk: 4_2_5 | Page: 2 | Score: 0.697
at run-time. Note that M can be very large (e.g., 21 million passages in our experiments, de- scribed in Section 4.1) and k is usually small, such as 20–100. 3.1 Overview Our dense passage retriever (DPR) uses a dense encoder EP (·) which maps any text passage to a d- dimensional real-valued vectors and builds an index for all the M passages that w

Rank: 3 | Chunk: 4_4_4 | Page: 4 | Score: 0.625
passages has the answer, the ques- tion will be discarded. For SQuAD and Natural Questions, since the original passages have been split and processed differently than our pool of candidate passages, we match and replace each gold passage with the corresponding passage in the candidate pool.7 We discard the questions when the matching is failed due

==========================================================================================
Q8: Why are sentence embeddings useful for semantic search?

Rank: 1 | Chunk: 4_1_2 | Page: 1 | Score: 0.586
been released at https://github.com/facebookresearch/DPR. 2For instance, the exact match score on SQuAD v1.1 drops from above 80% to less than 40% (Yang et al., 2019a). Retrieval in open-domain QA is usually imple- mented using TF-IDF or BM25 (Robertson and Zaragoza, 2009), which matches keywords efﬁ- ciently with an inverted index and can be seen

Rank: 2 | Chunk: 4_10_1 | Page: 10 | Score: 0.557
Indexing by latent semantic analysis. Jour- nal of the American society for information science, 41(6):391–407. Jacob Devlin, Ming-Wei Chang, Kenton Lee, and Kristina Toutanova. 2019. BERT: Pre-training of deep bidirectional transformers for language under- standing. In North American Association for Com- putational Linguistics (NAACL). David A Fer

Rank: 3 | Chunk: 2_2_0 | Page: 2 | Score: 0.528
most similar sentence pair in a collection of 10,000 sentences is reduced from 65 hours with BERT to the computation of 10,000 sentence embeddings (~5 seconds with SBERT) and computing cosine- similarity (~0.01 seconds). By using optimized index structures, ﬁnding the most similar Quora question can be reduced from 50 hours to a few milliseconds (J

==========================================================================================
Q9: What is the role of positional encoding in Transformers?

Rank: 1 | Chunk: 1_5_1 | Page: 5 | Score: 0.506
Applications of Attention in our Model The Transformer uses multi-head attention in three different ways: • In "encoder-decoder attention" layers, the queries come from the previous decoder layer, and the memory keys and values come from the output of the encoder. This allows every position in the decoder to attend over all positions in the input s

Rank: 2 | Chunk: 1_6_1 | Page: 6 | Score: 0.487
of the encoder and decoder stacks. The positional encodings have the same dimension dmodel as the embeddings, so that the two can be summed. There are many choices of positional encodings, learned and fixed [9]. In this work, we use sine and cosine functions of different frequencies: PE(pos,2i) = sin(pos/100002i/dmodel) PE(pos,2i+1) = cos(pos/10000

Rank: 3 | Chunk: 1_3_0 | Page: 3 | Score: 0.481
Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively. 3.1 Encoder and Decoder Stacks Encoder: The encoder is composed of a stack of N = 6 iden

==========================================================================================
Q10: How can a RAG system determine whether a claim is supported by evidence?

Rank: 1 | Chunk: 5_7_2 | Page: 7 | Score: 0.482
Dante is divided into 3 parts: the Inferno, the Purgatorio & the Purgatorio RAG-T Dante’s "Inferno" is the ﬁrst part of this epic poem RAG-S This 14th century work is divided into 3 sections: "Inferno", "Purgatorio" & "Paradiso" For 2-way classiﬁcation, we compare against Thorne and Vlachos [57], who train RoBERTa [35] to classify the claim as true

Rank: 2 | Chunk: 5_10_0 | Page: 10 | Score: 0.444
Broader Impact This work offers several positive societal beneﬁts over previous work: the fact that it is more strongly grounded in real factual knowledge (in this case Wikipedia) makes it “hallucinate” less with generations that are more factual, and offers more control and interpretability. RAG could be employed in a wide variety of scenarios wit

Rank: 3 | Chunk: 5_5_2 | Page: 5 | Score: 0.422
mutual dependence between the input and output [33]. We follow best practice and use pairwise comparative evaluation [34]. Evaluators are shown an answer and two generated questions, one from BART and one from RAG. They are then asked to pick one of four options—quuestion A is better, question B is better, both are good, or neither is good. 3.4 Fac

In [16]:
relevant_chunks = {
    "Q1": {"1_2_1", "1_6_2"},
    "Q2": {"1_4_0", "1_4_1", "1_4_2"},
    "Q3": {"1_5_0", "1_4_2"},
    "Q4": {"3_3_3", "3_4_0", "3_12_3"},
    "Q5": {"4_1_2", "4_2_4", "4_2_5"},
    "Q6": {"5_7_3", "5_9_3"},
    "Q7": {"4_2_5"},
    "Q8": {"2_2_0"},
    "Q9": {"1_6_1"},
    "Q10": {"5_7_2"}
}

In [17]:
def evaluate_retrieval(eval_questions, relevant_chunks, k=5):
    hit_rates = []
    reciprocal_ranks = []

    for i, query in enumerate(eval_questions, start=1):
        qid = f"Q{i}"

        if qid not in relevant_chunks:
            continue

        gold = relevant_chunks[qid]

        # Questions with no supporting evidence are evaluated
        # separately for abstention, not retrieval ranking.
        if not gold:
            continue

        results = retrieve(query, top_k=k)
        ranked_ids = results["chunk_id"].tolist()

        ranks = [
            rank
            for rank, chunk_id in enumerate(ranked_ids, start=1)
            if chunk_id in gold
        ]

        hit_rates.append(float(bool(ranks)))
        reciprocal_ranks.append(
            1 / min(ranks) if ranks else 0.0
        )

    return {
        "Evaluated answerable questions": len(hit_rates),
        f"Hit Rate@{k}": (
            sum(hit_rates) / len(hit_rates)
            if hit_rates else None
        ),
        "MRR": (
            sum(reciprocal_ranks) / len(reciprocal_ranks)
            if reciprocal_ranks else None
        )
    }

In [18]:

evaluate_retrieval(
    eval_questions,
    relevant_chunks,
    k=5
)

{'Evaluated answerable questions': 10,
 'Hit Rate@5': 1.0,
 'MRR': 0.8333333333333334}

In [19]:
import google.genai
import google.auth
MODEL_NAME = "gemini-3.8-flash"
print("Gemini SDK imported successfully")
print("google-auth version:", google.auth.__version__)

Gemini SDK imported successfully
google-auth version: 2.49.0

In [20]:
from google import genai

client = genai.Client(api_key=API_KEY)

interaction = client.interactions.create(
    model="gemini-3.8-flash",
    input="Explain how AI works in a few words"
)
print(interaction.output_text)

It learns patterns from massive data to make predictions.

In [21]:
def generate_rag_answer(query, top_k=5):

    # 1. Retrieve evidence
    results = retrieve(query, top_k=top_k)

    # 2. Format passages with traceable source metadata
    evidence_blocks = []

    for _, row in results.iterrows():
        evidence_blocks.append(
            f"[{row['chunk_id']}]\n"
            f"Source: {row['source']}\n"
            f"Page: {row['page']}\n"
            f"Passage: {row['text']}"
        )

    evidence = "\n\n".join(evidence_blocks)

    # 3. Generate an evidence-grounded answer
    prompt = f"""
You are a research assistant answering questions from research papers.

USER QUESTION:
{query}

RETRIEVED EVIDENCE:
{evidence}

INSTRUCTIONS:
1. Answer using only the retrieved evidence.
2. Cite supporting passages using their exact chunk IDs, e.g. [1_4_1].
3. Do not invent facts, citations, or page references.
4. If the evidence is insufficient, explicitly say what cannot be
   established from the provided passages.
5. Distinguish direct evidence from reasonable inference.
6. Write a concise, technically accurate answer.

ANSWER:
"""

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )

    return {
        "question": query,
        "answer": response.text,
        "retrieved_chunks": results
    }

In [22]:
query = "Why does the Transformer eliminate recurrence?"

result = generate_rag_answer(query)

print("QUESTION:")
print(result["question"])

print("\nGENERATED ANSWER:")
print(result["answer"])

print("\nRETRIEVED SOURCES:")
display(
    result["retrieved_chunks"][
        ["chunk_id", "source", "page", "similarity"]
    ]
)

QUESTION:
Why does the Transformer eliminate recurrence?

GENERATED ANSWER:
Based on the retrieved evidence, the Transformer eliminates recurrence to overcome the fundamental constraint of sequential computation inherent in recurrent models and to achieve the following benefits:

* **Significantly more parallelization:** Relying entirely on an attention mechanism rather than sequential computation allows computations to be parallelized across sequence positions [1_2_1].
* **Faster training and improved efficiency:** This increased parallelization enables the Transformer to be trained much faster, reaching a new state of the art in translation quality after as little as twelve hours of training on eight P100 GPUs [1_2_1].
* **Modeling dependencies directly:** The model can draw global dependencies between input and output purely through the attention mechanism without needing sequence-aligned recurrent networks [1_2_1, 1_2_3].

RETRIEVED SOURCES:

   chunk_id         source  page  similarity
4     1_2_1  Attention.pdf     2    0.345999
14    1_5_1  Attention.pdf     5    0.338284
8     1_3_0  Attention.pdf     3    0.296545
6     1_2_3  Attention.pdf     2    0.283676
7     1_2_4  Attention.pdf     2    0.267087

In [23]:
baseline_result = {
    "question": result["question"],
    "answer": result["answer"],
    "retrieved_chunk_ids": (
        result["retrieved_chunks"]["chunk_id"].tolist()
    )
}

print("Baseline answer saved in memory.")

Baseline answer saved in memory.

In [24]:
import json
import re

def verify_claims(answer, retrieved_chunks):

    evidence = []

    for _, row in retrieved_chunks.iterrows():
        evidence.append({
            "chunk_id": row["chunk_id"],
            "source": row["source"],
            "page": int(row["page"]),
            "text": row["text"]
        })

    prompt = f"""
You are a strict evidence verifier for a research-paper RAG system.

Your task is to evaluate factual claims in an answer using ONLY
the supplied evidence.

ANSWER:
{answer}

EVIDENCE:
{json.dumps(evidence, ensure_ascii=False)}

Instructions:
1. Split the answer into atomic factual claims.
2. Evaluate each claim independently.
3. Use exactly one verdict:
   - supported
   - contradicted
   - insufficient_evidence
4. A claim is supported only if the supplied passages entail it.
5. A claim is contradicted only if the passages conflict with it.
6. Use insufficient_evidence when neither support nor contradiction
   can be established.
7. Do not use your general knowledge to fill evidence gaps.
8. Return only valid JSON, with this structure:

{{
  "claims": [
    {{
      "claim": "An atomic factual claim",
      "verdict": "supported",
      "evidence_chunk_ids": ["1_2_1"],
      "reason": "Brief explanation based on the passage"
    }}
  ]
}}

For insufficient_evidence, use an empty evidence_chunk_ids list
unless a passage is relevant to explaining the evidence gap.
"""

    response = client.models.generate_content(
        model= MODEL_NAME,
        contents=prompt,
        config={
            "response_mime_type": "application/json"
        }
    )

    return json.loads(response.text)

In [25]:
verification = verify_claims(
    answer=result["answer"],
    retrieved_chunks=result["retrieved_chunks"]
)

for claim in verification["claims"]:
    print("\nClaim:", claim["claim"])
    print("Verdict:", claim["verdict"])
    print("Evidence:", claim["evidence_chunk_ids"])
    print("Reason:", claim["reason"])

Claim: The Transformer eschews recurrence to address the fundamental constraint of sequential computation.
Verdict: supported
Evidence: ['1_2_1']
Reason: Chunk 1_2_1 notes that 'The fundamental constraint of sequential computation, however, remains' in models using recurrence, and introduces the Transformer as 'a model architecture eschewing recurrence and instead relying entirely on an attention mechanism'.

Claim: The Transformer allows for significantly more parallelization.
Verdict: supported
Evidence: ['1_2_1']
Reason: Chunk 1_2_1 explicitly states: 'The Transformer allows for significantly more parallelization'.

Claim: The Transformer allows computations to be parallelized across sequence positions.
Verdict: insufficient_evidence
Evidence: ['1_2_1']
Reason: Chunk 1_2_1 states that the Transformer allows for significantly more parallelization, but it does not specify that computations are parallelized across sequence positions.

Claim: The increased parallelization enables the Transformer to be trained much faster and with improved efficiency.
Verdict: insufficient_evidence
Evidence: ['1_2_1']
Reason: Chunk 1_2_1 states the model can be trained in as little as twelve hours on eight P100 GPUs, but does not explicitly state that parallelization enables it to train 'much faster' or mention 'improved efficiency'.

Claim: The Transformer can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs.
Verdict: supported
Evidence: ['1_2_1']
Reason: Chunk 1_2_1 directly states that the Transformer 'can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs'.

Claim: The Transformer can draw global dependencies between input and output purely through the attention mechanism without needing sequence-aligned recurrent networks.
Verdict: supported
Evidence: ['1_2_1', '1_2_3']
Reason: Chunk 1_2_1 states that the model relies 'entirely on an attention mechanism to draw global dependencies between input and output', and chunk 1_2_3 confirms it computes representations 'without using sequence-aligned RNNs or convolution'.

In [26]:
row = chunks_df.loc[
    chunks_df["chunk_id"] == "1_2_1"
].iloc[0]

print(row["text"])

through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc- tion models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for significantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs. 2 Background The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for

In [27]:
def check_citation_ids(verification, retrieved_chunks):
    available_ids = set(
        retrieved_chunks["chunk_id"].astype(str)
    )

    for claim in verification["claims"]:
        cited_ids = claim.get("evidence_chunk_ids", [])

        invalid_ids = [
            cid for cid in cited_ids
            if cid not in available_ids
        ]

        claim["citation_ids_valid"] = not invalid_ids
        claim["invalid_citation_ids"] = invalid_ids

    return verification


verification = check_citation_ids(
    verification,
    result["retrieved_chunks"]
)

for claim in verification["claims"]:
    print(
        claim["verdict"],
        "| IDs valid:", claim["citation_ids_valid"],
        "| Claim:", claim["claim"]
    )

supported | IDs valid: True | Claim: The Transformer eschews recurrence to address the fundamental constraint of sequential computation.
supported | IDs valid: True | Claim: The Transformer allows for significantly more parallelization.
insufficient_evidence | IDs valid: True | Claim: The Transformer allows computations to be parallelized across sequence positions.
insufficient_evidence | IDs valid: True | Claim: The increased parallelization enables the Transformer to be trained much faster and with improved efficiency.
supported | IDs valid: True | Claim: The Transformer can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs.
supported | IDs valid: True | Claim: The Transformer can draw global dependencies between input and output purely through the attention mechanism without needing sequence-aligned recurrent networks.

In [28]:
def repair_claim(claim, top_k=5):
    # Search specifically for evidence supporting this claim
    results = retrieve(claim, top_k=top_k)

    evidence = [
        {
            "chunk_id": row["chunk_id"],
            "source": row["source"],
            "page": int(row["page"]),
            "text": row["text"]
        }
        for _, row in results.iterrows()
    ]

    prompt = f"""
You are repairing one factual claim in a research-paper answer.

ORIGINAL CLAIM:
{claim}

NEWLY RETRIEVED EVIDENCE:
{json.dumps(evidence, ensure_ascii=False)}

Rules:
- Use only the supplied evidence.
- If evidence supports the claim, return a concise revised claim.
- If evidence contradicts the claim, correct it using the evidence.
- If evidence is insufficient, do not invent a correction.
- Return JSON only, using this structure:

{{
  "revised_claim": "The revised claim or an empty string",
  "status": "repaired or unresolved",
  "evidence_chunk_ids": ["chunk_id"]
}}
"""

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config={"response_mime_type": "application/json"}
    )

    repair = json.loads(response.text)
    repair["retrieved_chunks"] = results

    return repair

In [29]:
repair_results = []

for claim_data in verification["claims"]:
    if claim_data["verdict"] == "supported":
        continue

    repair = repair_claim(claim_data["claim"])

    repair_results.append({
        "original_claim": claim_data["claim"],
        "original_verdict": claim_data["verdict"],
        "revised_claim": repair.get("revised_claim", ""),
        "repair_status": repair.get("status", "unresolved"),
        "evidence_chunk_ids": repair.get("evidence_chunk_ids", [])
    })

pd.DataFrame(repair_results)

,original_claim,original_verdict,revised_claim,repair_status,evidence_chunk_ids
0,The Transformer allows computations to be para...,insufficient_evidence,By eschewing recurrence and relying entirely o...,repaired,[1_2_1]
1,The increased parallelization enables the Tran...,insufficient_evidence,The Transformer allows for significantly more ...,repaired,"[1_2_1, 1_8_0]"

In [30]:
test_claim = (
    "The Transformer uses a genetic algorithm "
    "to optimize its attention weights."
)

test_verification = verify_claims(
    answer=test_claim,
    retrieved_chunks=retrieve(test_claim, top_k=5)
)

for claim in test_verification["claims"]:
    print("Claim:", claim["claim"])
    print("Verdict:", claim["verdict"])
    print("Evidence:", claim["evidence_chunk_ids"])
    print("Reason:", claim["reason"])

Claim: The Transformer uses a genetic algorithm to optimize its attention weights.
Verdict: insufficient_evidence
Evidence: []
Reason: The provided passages do not mention genetic algorithms or the optimization technique used for the attention weights.

In [31]:
repair_results = []

for claim_data in test_verification["claims"]:
    if claim_data["verdict"] == "supported":
        continue

    repair = repair_claim(claim_data["claim"])

    repair_results.append({
        "original_claim": claim_data["claim"],
        "original_verdict": claim_data["verdict"],
        "revised_claim": repair.get("revised_claim", ""),
        "repair_status": repair.get("status", "unresolved"),
        "evidence_chunk_ids": repair.get(
            "evidence_chunk_ids", []
        )
    })

display(pd.DataFrame(repair_results))

,original_claim,original_verdict,revised_claim,repair_status,evidence_chunk_ids
0,The Transformer uses a genetic algorithm to op...,insufficient_evidence,,unresolved,[]

In [32]:
def verify_repaired_claim(repair, top_k=5):
    revised_claim = repair.get("revised_claim", "").strip()

    # Nothing to verify if the claim remains unresolved
    if not revised_claim:
        return {
            "revised_claim": "",
            "final_verdict": "unresolved",
            "evidence_chunk_ids": []
        }

    # Verify the revision against the evidence retrieved during repair
    verification = verify_claims(
        answer=revised_claim,
        retrieved_chunks=repair["retrieved_chunks"]
    )

    claims = verification.get("claims", [])

    # Conservative handling: accept only if every returned claim
    # is supported by the retrieved evidence.
    all_supported = (
        len(claims) > 0
        and all(c.get("verdict") == "supported" for c in claims)
    )

    evidence_ids = list(dict.fromkeys(
        cid
        for claim in claims
        if claim.get("verdict") == "supported"
        for cid in claim.get("evidence_chunk_ids", [])
    ))

    return {
        "revised_claim": revised_claim if all_supported else "",
        "final_verdict": "supported" if all_supported else "unresolved",
        "evidence_chunk_ids": evidence_ids
    }

In [34]:
repair = repair_claim(
    "The Transformer uses a genetic algorithm to optimize its attention weights."
)

final_check = verify_repaired_claim(repair)
print(final_check)

{'revised_claim': '', 'final_verdict': 'unresolved', 'evidence_chunk_ids': []}

In [35]:
test_claim = (
    "In scaled dot-product attention, the query-key dot products "
    "are divided by the square root of the key dimension."
)

test_results = retrieve(test_claim, top_k=5)

for _, row in test_results.iterrows():
    print(f"\nChunk: {row['chunk_id']} | Page: {row['page']}")
    print(row["text"][:700])

Chunk: 1_4_2 | Page: 4
counteract this effect, we scale the dot products by 1 √dk . 3.2.2 Multi-Head Attention Instead of performing a single attention function with dmodel-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to dk, dk and dv dimensions, respectively. On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding dv-dimensional 4To illustrate why the dot products get large, assume that the components of q and k are independent random variables with mean 0 and variance 1. Then their dot product, q · k = Pdk i=1 qiki, has mean 0 and

Chunk: 1_4_0 | Page: 4
Scaled Dot-Product Attention Multi-Head Attention Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel. of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key. 3.2.1 Scaled Dot-Product Attention We call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of queries and keys of dimension dk, and values of dimension dv. We compute the dot products of the query with all keys, divide each by √dk, and apply a softmax function to obtain the weights on the values. In practice, we compute the attention funct

Chunk: 1_4_1 | Page: 4
as: Attention(Q, K, V ) = softmax(QKT √dk )V (1) The two most commonly used attention functions are additive attention [2], and dot-product (multi- plicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √dk . Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are similar in theoretical complexity, dot-product attention is much faster and more space-efficient in practice, since it can be implemented using highly optimized matrix multiplication code. While for small values of dk the two mechanisms perform similarly, additive attention outperforms dot product attenti

Chunk: 1_1_2 | Page: 1
of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the other person involved in nearly every detail. Niki designed, implemented, tuned and evaluated countless model variants in our original codebase and tensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and efficient inference and visualizations. Lukasz and Aidan spent countless long days designing various parts of and implementing tensor2tensor, replacing our earlier codebase, greatly improving results and massively accelerating our research. †Work performed while at Google Brain. ‡Work performed whi

Chunk: 1_9_1 | Page: 9
0.2 4.95 25.5 0.0 4.67 25.3 0.2 5.47 25.7 (E) positional embedding instead of sinusoids 4.92 25.7 big 6 1024 4096 16 0.3 300K 4.33 26.4 213 development set, newstest2013. We used beam search as described in the previous section, but no checkpoint averaging. We present these results in Table 3. In Table 3 rows (A), we vary the number of attention heads and the attention key and value dimensions, keeping the amount of computation constant, as described in Section 3.2.2. While single-head attention is 0.9 BLEU worse than the best setting, quality also drops off with too many heads. In Table 3 rows (B), we observe that reducing the attention key size dk hurts model quality. This suggests that de

In [36]:
test_verification = verify_claims(
    answer=test_claim,
    retrieved_chunks=test_results
)

print(json.dumps(test_verification, indent=2))

{
  "claims": [
    {
      "claim": "In scaled dot-product attention, the query-key dot products are divided by the square root of the key dimension.",
      "verdict": "supported",
      "evidence_chunk_ids": [
        "1_4_0"
      ],
      "reason": "Chunk 1_4_0 states that keys have dimension dk and that they 'compute the dot products of the query with all keys, divide each by \u221adk'."
    }
  ]
}

In [37]:
test_claim = (
    "In scaled dot-product attention, the query-key dot products "
    "are divided by the square root of the key dimension."
)

test_results = retrieve(test_claim, top_k=5)

for _, row in test_results.iterrows():
    print(f"\nChunk: {row['chunk_id']} | Page: {row['page']}")
    print(f"Similarity: {row['similarity']:.4f}")
    print(row["text"][:700])
    print("-" * 80)

Chunk: 1_4_2 | Page: 4
Similarity: 0.7165
counteract this effect, we scale the dot products by 1 √dk . 3.2.2 Multi-Head Attention Instead of performing a single attention function with dmodel-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to dk, dk and dv dimensions, respectively. On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding dv-dimensional 4To illustrate why the dot products get large, assume that the components of q and k are independent random variables with mean 0 and variance 1. Then their dot product, q · k = Pdk i=1 qiki, has mean 0 and
--------------------------------------------------------------------------------

Chunk: 1_4_0 | Page: 4
Similarity: 0.6530
Scaled Dot-Product Attention Multi-Head Attention Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel. of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key. 3.2.1 Scaled Dot-Product Attention We call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of queries and keys of dimension dk, and values of dimension dv. We compute the dot products of the query with all keys, divide each by √dk, and apply a softmax function to obtain the weights on the values. In practice, we compute the attention funct
--------------------------------------------------------------------------------

Chunk: 1_4_1 | Page: 4
Similarity: 0.6402
as: Attention(Q, K, V ) = softmax(QKT √dk )V (1) The two most commonly used attention functions are additive attention [2], and dot-product (multi- plicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √dk . Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are similar in theoretical complexity, dot-product attention is much faster and more space-efficient in practice, since it can be implemented using highly optimized matrix multiplication code. While for small values of dk the two mechanisms perform similarly, additive attention outperforms dot product attenti
--------------------------------------------------------------------------------

Chunk: 1_1_2 | Page: 1
Similarity: 0.4915
of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the other person involved in nearly every detail. Niki designed, implemented, tuned and evaluated countless model variants in our original codebase and tensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and efficient inference and visualizations. Lukasz and Aidan spent countless long days designing various parts of and implementing tensor2tensor, replacing our earlier codebase, greatly improving results and massively accelerating our research. †Work performed while at Google Brain. ‡Work performed whi
--------------------------------------------------------------------------------

Chunk: 1_9_1 | Page: 9
Similarity: 0.4428
0.2 4.95 25.5 0.0 4.67 25.3 0.2 5.47 25.7 (E) positional embedding instead of sinusoids 4.92 25.7 big 6 1024 4096 16 0.3 300K 4.33 26.4 213 development set, newstest2013. We used beam search as described in the previous section, but no checkpoint averaging. We present these results in Table 3. In Table 3 rows (A), we vary the number of attention heads and the attention key and value dimensions, keeping the amount of computation constant, as described in Section 3.2.2. While single-head attention is 0.9 BLEU worse than the best setting, quality also drops off with too many heads. In Table 3 rows (B), we observe that reducing the attention key size dk hurts model quality. This suggests that de
--------------------------------------------------------------------------------

In [38]:
test_verification = verify_claims(
    answer=test_claim,
    retrieved_chunks=test_results
)

print(json.dumps(test_verification, indent=2))

{
  "claims": [
    {
      "claim": "In scaled dot-product attention, the query-key dot products are divided by the square root of the key dimension.",
      "verdict": "supported",
      "evidence_chunk_ids": [
        "1_4_0"
      ],
      "reason": "Chunk 1_4_0 explains that in Scaled Dot-Product Attention, the keys have dimension dk, and the algorithm computes the dot products of the query with all keys and divides each by \u221adk."
    }
  ]
}

In [39]:
repairable_claim = (
    "In scaled dot-product attention, the query-key dot products "
    "are multiplied by the square root of the key dimension."
)

repairable_results = retrieve(repairable_claim, top_k=5)

for _, row in repairable_results.iterrows():
    print(f"\nChunk: {row['chunk_id']} | Page: {row['page']}")
    print(f"Similarity: {row['similarity']:.4f}")
    print(row["text"][:700])
    print("-" * 80)

Chunk: 1_4_2 | Page: 4
Similarity: 0.7157
counteract this effect, we scale the dot products by 1 √dk . 3.2.2 Multi-Head Attention Instead of performing a single attention function with dmodel-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to dk, dk and dv dimensions, respectively. On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding dv-dimensional 4To illustrate why the dot products get large, assume that the components of q and k are independent random variables with mean 0 and variance 1. Then their dot product, q · k = Pdk i=1 qiki, has mean 0 and
--------------------------------------------------------------------------------

Chunk: 1_4_0 | Page: 4
Similarity: 0.6487
Scaled Dot-Product Attention Multi-Head Attention Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel. of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key. 3.2.1 Scaled Dot-Product Attention We call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of queries and keys of dimension dk, and values of dimension dv. We compute the dot products of the query with all keys, divide each by √dk, and apply a softmax function to obtain the weights on the values. In practice, we compute the attention funct
--------------------------------------------------------------------------------

Chunk: 1_4_1 | Page: 4
Similarity: 0.6383
as: Attention(Q, K, V ) = softmax(QKT √dk )V (1) The two most commonly used attention functions are additive attention [2], and dot-product (multi- plicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √dk . Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are similar in theoretical complexity, dot-product attention is much faster and more space-efficient in practice, since it can be implemented using highly optimized matrix multiplication code. While for small values of dk the two mechanisms perform similarly, additive attention outperforms dot product attenti
--------------------------------------------------------------------------------

Chunk: 1_1_2 | Page: 1
Similarity: 0.4812
of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the other person involved in nearly every detail. Niki designed, implemented, tuned and evaluated countless model variants in our original codebase and tensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and efficient inference and visualizations. Lukasz and Aidan spent countless long days designing various parts of and implementing tensor2tensor, replacing our earlier codebase, greatly improving results and massively accelerating our research. †Work performed while at Google Brain. ‡Work performed whi
--------------------------------------------------------------------------------

Chunk: 1_9_1 | Page: 9
Similarity: 0.4263
0.2 4.95 25.5 0.0 4.67 25.3 0.2 5.47 25.7 (E) positional embedding instead of sinusoids 4.92 25.7 big 6 1024 4096 16 0.3 300K 4.33 26.4 213 development set, newstest2013. We used beam search as described in the previous section, but no checkpoint averaging. We present these results in Table 3. In Table 3 rows (A), we vary the number of attention heads and the attention key and value dimensions, keeping the amount of computation constant, as described in Section 3.2.2. While single-head attention is 0.9 BLEU worse than the best setting, quality also drops off with too many heads. In Table 3 rows (B), we observe that reducing the attention key size dk hurts model quality. This suggests that de
--------------------------------------------------------------------------------

In [40]:
repairable_verification = verify_claims(
    answer=repairable_claim,
    retrieved_chunks=repairable_results
)

print(json.dumps(repairable_verification, indent=2))

{
  "claims": [
    {
      "claim": "In scaled dot-product attention, the query-key dot products are multiplied by the square root of the key dimension.",
      "verdict": "contradicted",
      "evidence_chunk_ids": [
        "1_4_0",
        "1_4_1",
        "1_4_2"
      ],
      "reason": "The passages state that the dot products are divided by \u221adk (or scaled by 1/\u221adk), not multiplied by the square root of the key dimension."
    }
  ]
}

In [41]:
repair = repair_claim(
    claim=repairable_claim,
    top_k=5
)

print(json.dumps(
    {
        "original_claim": repairable_claim,
        "revised_claim": repair.get("revised_claim", ""),
        "repair_status": repair.get("status", "unresolved"),
        "evidence_chunk_ids": repair.get("evidence_chunk_ids", [])
    },
    indent=2
))

{
  "original_claim": "In scaled dot-product attention, the query-key dot products are multiplied by the square root of the key dimension.",
  "revised_claim": "In scaled dot-product attention, the query-key dot products are divided by the square root of the key dimension.",
  "repair_status": "repaired",
  "evidence_chunk_ids": [
    "1_4_0",
    "1_4_1"
  ]
}

In [43]:
final_check = verify_repaired_claim(repair)
print(json.dumps(final_check, indent=2))

{
  "revised_claim": "In scaled dot-product attention, the query-key dot products are divided by the square root of the key dimension.",
  "final_verdict": "supported",
  "evidence_chunk_ids": [
    "1_4_0"
  ]
}

In [44]:
import pandas as pd

eval_data = [
    # Directly answerable
    {"id": 1, "question": "Why does the Transformer eliminate recurrence?",
     "category": "answerable"},
    {"id": 2, "question": "How does scaled dot-product attention work?",
     "category": "answerable"},
    {"id": 3, "question": "What is the purpose of multi-head attention?",
     "category": "answerable"},
    {"id": 4, "question": "How does Bahdanau attention calculate alignment scores?",
     "category": "answerable"},
    {"id": 5, "question": "What is the difference between sparse and dense retrieval?",
     "category": "answerable"},
    {"id": 6, "question": "How does RAG combine retrieval and generation?",
     "category": "answerable"},
    {"id": 7, "question": "How does DPR represent questions and passages?",
     "category": "answerable"},
    {"id": 8, "question": "Why are sentence embeddings useful for semantic search?",
     "category": "answerable"},
    {"id": 9, "question": "What is the role of positional encoding?",
     "category": "answerable"},
    {"id": 10, "question": "How does RAG use retrieved passages to generate answers?",
     "category": "answerable"},
    {"id": 11, "question": "What is additive attention?",
     "category": "answerable"},
    {"id": 12, "question": "How is dot-product attention computationally efficient?",
     "category": "answerable"},
    {"id": 13, "question": "What is the purpose of the encoder-decoder architecture in neural machine translation?",
     "category": "answerable"},
    {"id": 14, "question": "What is the role of the softmax function in scaled dot-product attention?",
     "category": "answerable"},
    {"id": 15, "question": "How are query, key, and value vectors used in attention?",
     "category": "answerable"},

    # Incorrect claims that should be repairable
    {"id": 16, "question": "In scaled dot-product attention, are query-key dot products multiplied by the square root of the key dimension?",
     "category": "repairable"},
    {"id": 17, "question": "Does the Transformer rely on recurrence to process sequences?",
     "category": "repairable"},
    {"id": 18, "question": "Does multi-head attention use only one learned projection of queries, keys, and values?",
     "category": "repairable"},
    {"id": 19, "question": "Does DPR encode questions and passages using exactly the same encoder parameters?",
     "category": "repairable"},
    {"id": 20, "question": "Does Sentence-BERT require comparing every pair of sentences with a cross-encoder at search time?",
     "category": "repairable"},
    {"id": 21, "question": "Does RAG generate answers without conditioning on retrieved documents?",
     "category": "repairable"},
    {"id": 22, "question": "Does positional encoding provide the Transformer with no information about token positions?",
     "category": "repairable"},
    {"id": 23, "question": "Does additive attention compute compatibility using a dot product alone?",
     "category": "repairable"},

    # Claims/questions that may be unanswerable from this corpus
    {"id": 24, "question": "What exact GPU temperature did the authors observe during Transformer training?",
     "category": "insufficient_evidence"},
    {"id": 25, "question": "What was the electricity cost of training the original RAG model?",
     "category": "insufficient_evidence"},
    {"id": 26, "question": "What exact salary did each author receive while conducting the research?",
     "category": "insufficient_evidence"},
    {"id": 27, "question": "What was the authors' private opinion of every competing retrieval system?",
     "category": "insufficient_evidence"},
    {"id": 28, "question": "What was the precise network latency of every experiment in the DPR paper?",
     "category": "insufficient_evidence"},
    {"id": 29, "question": "What exact hardware temperature was recorded during Sentence-BERT experiments?",
     "category": "insufficient_evidence"},
    {"id": 30, "question": "What private discussions led the authors to select their final model architectures?",
     "category": "insufficient_evidence"},
]

eval_df = pd.DataFrame(eval_data)
display(eval_df)

,id,question,category
0,1,Why does the Transformer eliminate recurrence?,answerable
1,2,How does scaled dot-product attention work?,answerable
2,3,What is the purpose of multi-head attention?,answerable
3,4,How does Bahdanau attention calculate alignmen...,answerable
4,5,What is the difference between sparse and dens...,answerable
5,6,How does RAG combine retrieval and generation?,answerable
6,7,How does DPR represent questions and passages?,answerable
7,8,Why are sentence embeddings useful for semanti...,answerable
8,9,What is the role of positional encoding?,answerable
9,10,How does RAG use retrieved passages to generat...,answerable
10,11,What is additive attention?,answerable
11,12,How is dot-product attention computationally e...,answerable
12,13,What is the purpose of the encoder-decoder arc...,answerable
13,14,What is the role of the softmax function in sc...,answerable
14,15,"How are query, key, and value vectors used in ...",answerable
15,16,"In scaled dot-product attention, are query-key...",repairable
16,17,Does the Transformer rely on recurrence to pro...,repairable
17,18,Does multi-head attention use only one learned...,repairable
18,19,Does DPR encode questions and passages using e...,repairable
19,20,Does Sentence-BERT require comparing every pai...,repairable
20,21,Does RAG generate answers without conditioning...,repairable
21,22,Does positional encoding provide the Transform...,repairable
22,23,Does additive attention compute compatibility ...,repairable
23,24,What exact GPU temperature did the authors obs...,insufficient_evidence
24,25,What was the electricity cost of training the ...,insufficient_evidence
25,26,What exact salary did each author receive whil...,insufficient_evidence
26,27,What was the authors' private opinion of every...,insufficient_evidence
27,28,What was the precise network latency of every ...,insufficient_evidence
28,29,What exact hardware temperature was recorded d...,insufficient_evidence
29,30,What private discussions led the authors to se...,insufficient_evidence

In [45]:
retrieval_records = []

for item in eval_data:
    results = retrieve(item["question"], top_k=5)

    for rank, (_, row) in enumerate(results.iterrows(), start=1):
        retrieval_records.append({
            "question_id": item["id"],
            "question": item["question"],
            "category": item["category"],
            "rank": rank,
            "chunk_id": row["chunk_id"],
            "source": row["source"],
            "page": int(row["page"]),
            "similarity": float(row["similarity"]),
            "text": row["text"]
        })

retrieval_df = pd.DataFrame(retrieval_records)

print("Questions:", len(eval_df))
print("Retrieved passages:", len(retrieval_df))

display(retrieval_df.head(10))

Questions: 30
Retrieved passages: 150

,question_id,question,category,rank,chunk_id,source,page,similarity,text
0,1,Why does the Transformer eliminate recurrence?,answerable,1,1_2_1,Attention.pdf,2,0.345999,through factorization tricks [21] and conditio...
1,1,Why does the Transformer eliminate recurrence?,answerable,2,1_5_1,Attention.pdf,5,0.338284,Applications of Attention in our Model The Tra...
2,1,Why does the Transformer eliminate recurrence?,answerable,3,1_3_0,Attention.pdf,3,0.296545,Figure 1: The Transformer - model architecture...
3,1,Why does the Transformer eliminate recurrence?,answerable,4,1_2_3,Attention.pdf,2,0.283676,in order to compute a representation of the se...
4,1,Why does the Transformer eliminate recurrence?,answerable,5,1_2_4,Attention.pdf,2,0.267087,encoder maps an input sequence of symbol repre...
5,2,How does scaled dot-product attention work?,answerable,1,1_4_2,Attention.pdf,4,0.666730,"counteract this effect, we scale the dot produ..."
6,2,How does scaled dot-product attention work?,answerable,2,1_4_1,Attention.pdf,4,0.642469,"as: Attention(Q, K, V ) = softmax(QKT √dk )V (..."
7,2,How does scaled dot-product attention work?,answerable,3,1_4_0,Attention.pdf,4,0.617157,Scaled Dot-Product Attention Multi-Head Attent...
8,2,How does scaled dot-product attention work?,answerable,4,1_1_2,Attention.pdf,1,0.554508,of this work. Noam proposed scaled dot-product...
9,2,How does scaled dot-product attention work?,answerable,5,1_5_1,Attention.pdf,5,0.447338,Applications of Attention in our Model The Tra...

In [46]:
output_dir = Path("/content/drive/MyDrive/Colab Notebooks/Project/Data")
output_dir.mkdir(parents=True, exist_ok=True)

eval_df.to_csv(
    output_dir / "eval_questions.csv",
    index=False
)

retrieval_df.to_json(
    output_dir / "eval_retrieval_candidates.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

print("Saved evaluation questions and retrieval candidates.")

Saved evaluation questions and retrieval candidates.

In [47]:
# Display the five retrieved passages for one question at a time.

def inspect_question(question_id):
    rows = retrieval_df[
        retrieval_df["question_id"] == question_id
    ].sort_values("rank")

    if rows.empty:
        print("Question ID not found.")
        return

    print("Question:", rows.iloc[0]["question"])
    print("Category:", rows.iloc[0]["category"])

    for _, row in rows.iterrows():
        print(
            f"\nRank {row['rank']} | "
            f"Chunk: {row['chunk_id']} | "
            f"Page: {row['page']} | "
            f"Similarity: {row['similarity']:.3f}"
        )
        print(row["text"])
        print("-" * 80)

In [48]:
from pathlib import Path

review_path = Path(
    "/content/drive/MyDrive/Colab Notebooks/Project/Data"
    "all_questions_evidence_review.md"
)

with open(review_path, "w", encoding="utf-8") as f:
    f.write("# RAG Evaluation: Evidence Review\n\n")

    for question_id in sorted(retrieval_df["question_id"].unique()):
        rows = (
            retrieval_df[
                retrieval_df["question_id"] == question_id
            ]
            .sort_values("rank")
        )

        first = rows.iloc[0]

        f.write(f"## Question {question_id}\n\n")
        f.write(f"**Question:** {first['question']}\n\n")
        f.write(f"**Original category:** {first['category']}\n\n")

        for _, row in rows.iterrows():
            f.write(
                f"### Rank {row['rank']} — "
                f"{row['chunk_id']} "
                f"(page {row['page']}, "
                f"similarity {row['similarity']:.3f})\n\n"
            )
            f.write(f"**Source:** {row['source']}\n\n")
            f.write(row["text"].strip() + "\n\n")
            f.write("---\n\n")

print(f"Saved review file: {review_path}")
print(f"Questions: {retrieval_df['question_id'].nunique()}")
print(f"Passages: {len(retrieval_df)}")

Saved review file: /content/drive/MyDrive/Colab Notebooks/Project/Dataall_questions_evidence_review.md
Questions: 30
Passages: 150

In [49]:
from google.colab import files

files.download(
    "/content/drive/MyDrive/Colab Notebooks/"
    "Project/Dataall_questions_evidence_review.md"
)

In [63]:
!pip -q install -U sentence-transformers

from sentence_transformers import CrossEncoder

nli_model = CrossEncoder(
    "cross-encoder/nli-deberta-v3-xsmall",
    device="cpu"
)

print("Local NLI model loaded.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 740.6/740.6 kB 14.9 MB/s eta 0:00:00

config.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  283MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

spm.model: reconstructing file:   0%|          |  0.00B / 2.46MB

spm.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/8.66M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

Local NLI model loaded.

In [65]:
import numpy as np

NLI_LABELS = ["contradiction", "entailment", "neutral"]

def local_verify_claim(claim, retrieved_chunks):
    pairs = [
        (str(row["text"]), claim)
        for _, row in retrieved_chunks.iterrows()
    ]

    scores = nli_model.predict(pairs)

    best = None

    for i, (_, row) in enumerate(retrieved_chunks.iterrows()):
        logits = scores[i]
        probabilities = np.exp(logits - np.max(logits))
        probabilities = probabilities / probabilities.sum()

        result = {
            "chunk_id": str(row["chunk_id"]),
            "text": row["text"],
            "scores": dict(zip(
                NLI_LABELS, probabilities.astype(float)
            )),
            "predicted_label": NLI_LABELS[int(np.argmax(logits))]
        }

        # Find the passage with the strongest entailment score.
        if best is None or (
            result["scores"]["entailment"]
            > best["scores"]["entailment"]
        ):
            best = result

    if best is None:
        return {
            "claim": claim,
            "verdict": "insufficient_evidence",
            "evidence_chunk_id": None,
            "scores": None
        }

    verdict_map = {
        "entailment": "supported",
        "contradiction": "contradicted",
        "neutral": "insufficient_evidence"
    }

    return {
        "claim": claim,
        "verdict": verdict_map[best["predicted_label"]],
        "evidence_chunk_id": best["chunk_id"],
        "scores": best["scores"],
        "evidence_text": best["text"]
    }

In [66]:
test_claim = (
    "The Transformer uses a genetic algorithm "
    "to optimize its attention weights."
)

test_chunks = retrieve(test_claim, top_k=5)

local_result = local_verify_claim(test_claim, test_chunks)

print("Verdict:", local_result["verdict"])
print("Evidence chunk:", local_result["evidence_chunk_id"])
print("Scores:", local_result["scores"])
print("Evidence:", local_result["evidence_text"][:500])

Verdict: insufficient_evidence
Evidence chunk: 1_5_0
Scores: {'contradiction': np.float64(0.2692802846431732), 'entailment': np.float64(0.022103849798440933), 'neutral': np.float64(0.7086158394813538)}
Evidence: output values. These are concatenated and once again projected, resulting in the final values, as depicted in Figure 2. Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions. With a single attention head, averaging inhibits this. MultiHead(Q, K, V ) = Concat(head1, ..., headh)W O where headi = Attention(QW Q i , KW K i , V W V i ) Where the projections are parameter matrices W Q i ∈Rdmodel×dk, W K i ∈Rdmodel×dk, W V

In [67]:
def local_verify_claim(claim, retrieved_chunks):
    if retrieved_chunks.empty:
        return {
            "claim": claim,
            "verdict": "insufficient_evidence",
            "evidence_chunk_id": None
        }

    pairs = [
        (str(row["text"]), claim)
        for _, row in retrieved_chunks.iterrows()
    ]

    logits = nli_model.predict(pairs)

    # Convert logits to probabilities for each passage.
    probs = []
    for row_logits in logits:
        p = np.exp(row_logits - np.max(row_logits))
        probs.append(p / p.sum())

    probs = np.asarray(probs)

    # Class order: contradiction, entailment, neutral.
    best_contradiction = int(np.argmax(probs[:, 0]))
    best_entailment = int(np.argmax(probs[:, 1]))

    max_contradiction = float(probs[:, 0].max())
    max_entailment = float(probs[:, 1].max())

    # Conservative thresholds; validate these on a manually
    # labelled sample before using them in reported results.
    threshold = 0.70

    if max_contradiction >= threshold:
        idx = best_contradiction
        verdict = "contradicted"
    elif max_entailment >= threshold:
        idx = best_entailment
        verdict = "supported"
    else:
        idx = int(np.argmax(probs[:, 2]))
        verdict = "insufficient_evidence"

    return {
        "claim": claim,
        "verdict": verdict,
        "evidence_chunk_id": str(
            retrieved_chunks.iloc[idx]["chunk_id"]
        ),
        "scores": {
            "contradiction": float(probs[idx, 0]),
            "entailment": float(probs[idx, 1]),
            "neutral": float(probs[idx, 2])
        },
        "evidence_text": str(retrieved_chunks.iloc[idx]["text"])
    }

In [68]:
test_chunks = retrieve(
    "The Transformer uses a genetic algorithm to optimize its attention weights.",
    top_k=5
)

result = local_verify_claim(test_claim, test_chunks)

print("Verdict:", result["verdict"])
print("Evidence chunk:", result["evidence_chunk_id"])
print("Scores:", result["scores"])

Verdict: contradicted
Evidence chunk: 1_2_1
Scores: {'contradiction': 0.8646996021270752, 'entailment': 0.002131580375134945, 'neutral': 0.13316881656646729}

In [69]:
import pandas as pd

repairable = [
    item for item in eval_data
    if item["category"] == "repairable"
]

rows = []

for item in repairable:
    claim = item["question"]
    chunks = retrieve(claim, top_k=5)
    result = local_verify_claim(claim, chunks)

    rows.append({
        "question_id": item["id"],
        "claim": claim,
        "predicted_verdict": result["verdict"],
        "evidence_chunk_id": result["evidence_chunk_id"],
        "scores": result.get("scores")
    })

local_results_df = pd.DataFrame(rows)
display(local_results_df)

,question_id,claim,predicted_verdict,evidence_chunk_id,scores
0,16,"In scaled dot-product attention, are query-key...",contradicted,1_4_2,"{'contradiction': 0.7060143351554871, 'entailm..."
1,17,Does the Transformer rely on recurrence to pro...,contradicted,1_1_0,"{'contradiction': 0.7951224446296692, 'entailm..."
2,18,Does multi-head attention use only one learned...,contradicted,1_4_2,"{'contradiction': 0.9868631362915039, 'entailm..."
3,19,Does DPR encode questions and passages using e...,contradicted,4_9_2,"{'contradiction': 0.8666514754295349, 'entailm..."
4,20,Does Sentence-BERT require comparing every pai...,contradicted,2_8_4,"{'contradiction': 0.753334105014801, 'entailme..."
5,21,Does RAG generate answers without conditioning...,insufficient_evidence,5_8_2,"{'contradiction': 0.03275170177221298, 'entail..."
6,22,Does positional encoding provide the Transform...,contradicted,1_9_0,"{'contradiction': 0.9742032289505005, 'entailm..."
7,23,Does additive attention compute compatibility ...,contradicted,1_4_2,"{'contradiction': 0.8063765168190002, 'entailm..."

In [70]:
claim_map = {
    16: "In scaled dot-product attention, query-key dot products are multiplied by the square root of the key dimension.",
    17: "The Transformer relies on recurrence to process sequences.",
    18: "Multi-head attention uses only one learned projection of queries, keys, and values.",
    19: "DPR encodes questions and passages using exactly the same encoder parameters.",
    20: "Sentence-BERT requires comparing every pair of sentences with a cross-encoder at search time.",
    21: "RAG generates answers without conditioning on retrieved documents.",
    22: "Positional encoding provides the Transformer with no information about token positions.",
    23: "Additive attention computes compatibility using a dot product alone."
}

ground_truth = {qid: "contradicted" for qid in claim_map}

rows = []

for qid, claim in claim_map.items():
    chunks = retrieve(claim, top_k=5)
    result = local_verify_claim(claim, chunks)

    rows.append({
        "question_id": qid,
        "claim": claim,
        "ground_truth": ground_truth[qid],
        "prediction": result["verdict"],
        "correct": result["verdict"] == ground_truth[qid],
        "evidence_chunk_id": result["evidence_chunk_id"]
    })

claim_eval_df = pd.DataFrame(rows)

display(claim_eval_df)
print("Accuracy:", round(claim_eval_df["correct"].mean(), 3))

,question_id,claim,ground_truth,prediction,correct,evidence_chunk_id
0,16,"In scaled dot-product attention, query-key dot...",contradicted,insufficient_evidence,False,1_4_1
1,17,The Transformer relies on recurrence to proces...,contradicted,contradicted,True,1_2_1
2,18,Multi-head attention uses only one learned pro...,contradicted,contradicted,True,1_4_2
3,19,DPR encodes questions and passages using exact...,contradicted,contradicted,True,4_3_0
4,20,Sentence-BERT requires comparing every pair of...,contradicted,insufficient_evidence,False,2_2_3
5,21,RAG generates answers without conditioning on ...,contradicted,contradicted,True,5_4_4
6,22,Positional encoding provides the Transformer w...,contradicted,contradicted,True,1_9_0
7,23,Additive attention computes compatibility usin...,contradicted,contradicted,True,1_4_2

Accuracy: 0.75

In [72]:

claim_eval_df.to_csv(
    OUT_DIR / "local_claim_verification.csv",
    index=False
)

In [74]:
failure_claims = {
    16: claim_map[16],
    20: claim_map[20],
}

for qid, claim in failure_claims.items():
    print(f"\n{'=' * 70}\nQ{qid}: {claim}\n")

    chunks = retrieve(claim, top_k=5)
    pairs = [(str(row["text"]), claim) for _, row in chunks.iterrows()]
    logits = nli_model.predict(pairs)

    for i, (_, row) in enumerate(chunks.iterrows()):
        p = np.exp(logits[i] - np.max(logits[i]))
        p = p / p.sum()

        print(
            f"\nChunk: {row['chunk_id']} | "
            f"contradiction={p[0]:.3f}, "
            f"entailment={p[1]:.3f}, "
            f"neutral={p[2]:.3f}"
        )
        print(str(row["text"])[:500])

======================================================================
Q16: In scaled dot-product attention, query-key dot products are multiplied by the square root of the key dimension.


Chunk: 1_4_2 | contradiction=0.267, entailment=0.008, neutral=0.724
counteract this effect, we scale the dot products by 1 √dk . 3.2.2 Multi-Head Attention Instead of performing a single attention function with dmodel-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to dk, dk and dv dimensions, respectively. On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding dv-dimensional 4To il

Chunk: 1_4_0 | contradiction=0.201, entailment=0.006, neutral=0.793
Scaled Dot-Product Attention Multi-Head Attention Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel. of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key. 3.2.1 Scaled Dot-Product Attention We call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of queries and keys of dimension dk, and values of

Chunk: 1_4_1 | contradiction=0.008, entailment=0.002, neutral=0.989
as: Attention(Q, K, V ) = softmax(QKT √dk )V (1) The two most commonly used attention functions are additive attention [2], and dot-product (multi- plicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √dk . Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are similar in theoretical complexity, dot-product attention is much faster and more space-efficient in practi

Chunk: 1_1_2 | contradiction=0.090, entailment=0.002, neutral=0.908
of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the other person involved in nearly every detail. Niki designed, implemented, tuned and evaluated countless model variants in our original codebase and tensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and efficient inference and visualizations. Lukasz and Aidan spent countless long days designing variou

Chunk: 1_9_1 | contradiction=0.187, entailment=0.043, neutral=0.770
0.2 4.95 25.5 0.0 4.67 25.3 0.2 5.47 25.7 (E) positional embedding instead of sinusoids 4.92 25.7 big 6 1024 4096 16 0.3 300K 4.33 26.4 213 development set, newstest2013. We used beam search as described in the previous section, but no checkpoint averaging. We present these results in Table 3. In Table 3 rows (A), we vary the number of attention heads and the attention key and value dimensions, keeping the amount of computation constant, as described in Section 3.2.2. While single-head attention

======================================================================
Q20: Sentence-BERT requires comparing every pair of sentences with a cross-encoder at search time.


Chunk: 2_5_4 | contradiction=0.044, entailment=0.007, neutral=0.949
10-fold cross-validation setup gives a performance that is nearly on-par with BERT. However, in the cross-topic evaluation, we ob- serve a performance drop of SBERT by about 7 points Spearman correlation. To be considered similar, arguments should address the same claims and provide the same reasoning. BERT is able to use attention to compare directly both sentences (e.g. word-by-word comparison), while SBERT must map individual sentences from an unseen topic to a vector space such that argument

Chunk: 2_1_2 | contradiction=0.058, entailment=0.015, neutral=0.927
retrieval via semantic search. BERT set new state-of-the-art performance on various sentence classiﬁcation and sentence-pair regression tasks. BERT uses a cross-encoder: Two sentences are passed to the transformer network and the target value is predicted. However, this setup is unsuitable for various pair regression tasks due to too many possible combinations. Finding in a collection of n = 10 000 sentences the pair with the highest similarity requires with BERT n·(n−1)/2 = 49 995 000 inference

Chunk: 2_7_1 | contradiction=0.026, entailment=0.002, neutral=0.972
well sentiment information: We observe large improvements for all sentiment tasks (MR, CR, and SST) from SentEval in comparison to InferSent and Universal Sentence Encoder. The only dataset where SBERT is signiﬁcantly worse than Universal Sentence Encoder is the TREC dataset. Universal Sentence Encoder was pre-trained on question-answering data, which ap- pears to be beneﬁcial for the question-type classi- ﬁcation task of the TREC dataset. Average BERT embeddings or using the CLS- token output f

Chunk: 2_2_3 | contradiction=0.014, entailment=0.000, neutral=0.985
BERT network structure is that no independent sentence embed- dings are computed, which makes it difﬁcult to de- rive sentence embeddings from BERT. To bypass this limitations, researchers passed single sen- tences through BERT and then derive a ﬁxed sized vector by either averaging the outputs (similar to average word embeddings) or by using the output of the special CLS token (for example: May et al. (2019); Zhang et al. (2019); Qiao et al. (2019)). These two options are also provided by the p

Chunk: 2_4_3 | contradiction=0.355, entailment=0.023, neutral=0.622
cosine-similarity of the sentence embeddings and the gold labels. The setup for the other sentence embedding methods is equivalent, the similarity is computed by cosine- similarity. The results are depicted in Table 1. The results shows that directly using the output of BERT leads to rather poor performances. Av- eraging the BERT embeddings achieves an aver- age correlation of only 54.81, and using the CLS- token output only achieves an average correlation of 29.19. Both are worse than computing

In [75]:
corrected_claims = {
    16: (
        "Scaled dot-product attention divides query-key dot products "
        "by the square root of the key dimension."
    ),
    20: (
        "Sentence-BERT computes sentence embeddings independently, "
        "allowing semantic search using vector similarity instead "
        "of comparing every sentence pair with a cross-encoder."
    ),
}

for qid, corrected in corrected_claims.items():
    print(f"\nQ{qid}: {corrected}")

    chunks = retrieve(corrected, top_k=5)
    result = local_verify_claim(corrected, chunks)

    print("Verdict:", result["verdict"])
    print("Evidence chunk:", result["evidence_chunk_id"])
    print("Scores:", result.get("scores"))
    print("Evidence:", result.get("evidence_text", "")[:400])

Q16: Scaled dot-product attention divides query-key dot products by the square root of the key dimension.
Verdict: insufficient_evidence
Evidence chunk: 1_4_1
Scores: {'contradiction': 0.007031853776425123, 'entailment': 0.0023952254559844732, 'neutral': 0.9905728697776794}
Evidence: as: Attention(Q, K, V ) = softmax(QKT √dk )V (1) The two most commonly used attention functions are additive attention [2], and dot-product (multi- plicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √dk . Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are simila

Q20: Sentence-BERT computes sentence embeddings independently, allowing semantic search using vector similarity instead of comparing every sentence pair with a cross-encoder.
Verdict: insufficient_evidence
Evidence chunk: 2_1_3
Scores: {'contradiction': 0.003949328325688839, 'entailment': 0.0016989981522783637, 'neutral': 0.9943516254425049}
Evidence: map each sentence to a vec- tor space such that semantically similar sentences are close. Researchers have started to input indi- vidual sentences into BERT and to derive ﬁxed- size sentence embeddings. The most commonly used approach is to average the BERT output layer (known as BERT embeddings) or by using the out- put of the ﬁrst token (the [CLS] token). As we will show, this common practice yi

In [76]:
abstention_questions = {
    24: "What exact GPU temperature did the authors observe during Transformer training?",
    25: "What was the electricity cost of training the original RAG model?",
    26: "What exact salary did each author receive while conducting the research?",
    27: "What was the authors' private opinion of every competing retrieval system?",
    28: "What was the precise network latency of every experiment in the DPR paper?",
    29: "What exact hardware temperature was recorded during Sentence-BERT experiments?",
    30: "What private discussions led the authors to select their final model architectures?"
}

abstention_rows = []

for qid, question in abstention_questions.items():
    chunks = retrieve(question, top_k=5)

    # Check the question against the retrieved passages.
    result = local_verify_claim(question, chunks)

    abstention_rows.append({
        "question_id": qid,
        "question": question,
        "predicted_verdict": result["verdict"],
        "evidence_chunk_id": result["evidence_chunk_id"]
    })

abstention_df = pd.DataFrame(abstention_rows)
display(abstention_df)

,question_id,question,predicted_verdict,evidence_chunk_id
0,24,What exact GPU temperature did the authors obs...,contradicted,1_9_0
1,25,What was the electricity cost of training the ...,contradicted,5_8_0
2,26,What exact salary did each author receive whil...,contradicted,5_7_0
3,27,What was the authors' private opinion of every...,contradicted,4_10_3
4,28,What was the precise network latency of every ...,contradicted,3_14_0
5,29,What exact hardware temperature was recorded d...,contradicted,2_4_0
6,30,What private discussions led the authors to se...,contradicted,1_9_0

In [78]:
print("Label mapping:", nli_model.model.config.id2label)
print("Reverse mapping:", nli_model.model.config.label2id)
print("Number of labels:", nli_model.model.config.num_labels)

Label mapping: {0: 'contradiction', 1: 'entailment', 2: 'neutral'}
Reverse mapping: {'contradiction': 0, 'entailment': 1, 'neutral': 2}
Number of labels: 3

In [81]:
import pandas as pd

abstention_rows = []

for qid, question in abstention_questions.items():
    retrieved = retrieve(question, top_k=5)

    top = retrieved.iloc[0]

    abstention_rows.append({
        "question_id": qid,
        "question": question,
        "top_retrieval_similarity": float(top["similarity"]),
        "top_chunk_id": top["chunk_id"],
        "top_chunk_text": top["text"],
        "expected_verdict": "insufficient_evidence",
        "needs_manual_review": True
    })

abstention_df = pd.DataFrame(abstention_rows)

display(
    abstention_df[
        [
            "question_id",
            "top_retrieval_similarity",
            "top_chunk_id",
            "expected_verdict",
            "needs_manual_review"
        ]
    ]
)

,question_id,top_retrieval_similarity,top_chunk_id,expected_verdict,needs_manual_review
0,24,0.480691,1_8_3,insufficient_evidence,True
1,25,0.332588,5_8_0,insufficient_evidence,True
2,26,0.246022,5_7_0,insufficient_evidence,True
3,27,0.458209,4_4_4,insufficient_evidence,True
4,28,0.394448,4_8_3,insufficient_evidence,True
5,29,0.397497,2_4_0,insufficient_evidence,True
6,30,0.278732,5_14_3,insufficient_evidence,True

In [82]:
# Inspect all five retrieved passages for each unanswerable question.
review_rows = []

for qid, question in abstention_questions.items():
    retrieved = retrieve(question, top_k=5)

    for rank, (_, chunk) in enumerate(retrieved.iterrows(), start=1):
        review_rows.append({
            "question_id": qid,
            "question": question,
            "rank": rank,
            "similarity": float(chunk["similarity"]),
            "chunk_id": chunk["chunk_id"],
            "paper": chunk["title"],
            "evidence_text": chunk["text"]
        })

review_df = pd.DataFrame(review_rows)

display(
    review_df[
        ["question_id", "rank", "similarity", "chunk_id",
         "paper", "evidence_text"]
    ].sort_values(["question_id", "rank"])
)

,question_id,rank,similarity,chunk_id,paper,evidence_text
0,24,1,0.480691,1_8_3,Attention,"to input length + 50, but terminate early when..."
1,24,2,0.373035,1_8_0,Attention,Table 2: The Transformer achieves better BLEU ...
2,24,3,0.355586,1_8_1,Attention,is added to the sub-layer input and normalized...
3,24,4,0.336409,4_7_5,ODQA,"allowed, we ﬁne-tune the reader trained on Nat..."
4,24,5,0.315064,1_9_0,Attention,Table 3: Variations on the Transformer archite...
5,25,1,0.332588,5_8_0,RAG,Table 4: Human assessments for the Jeopardy Qu...
6,25,2,0.331420,5_17_2,RAG,"is sufﬁciently fast on CPU, so we store docume..."
7,25,3,0.303838,5_4_0,RAG,minimize the negative marginal log-likelihood ...
8,25,4,0.287330,1_8_0,Attention,Table 2: The Transformer achieves better BLEU ...
9,25,5,0.283530,5_6_2,RAG,that RAG generations are more diverse than BAR...
10,26,1,0.246022,5_7_0,RAG,Document 1: his works are considered classics ...
11,26,2,0.219654,5_7_2,RAG,"Dante is divided into 3 parts: the Inferno, th..."
12,26,3,0.194126,4_8_4,ODQA,longer passages compared to DPR (288 word piec...
13,26,4,0.182474,5_10_0,RAG,Broader Impact This work offers several positi...
14,26,5,0.170675,5_6_1,RAG,21.4 40.8 44.2 to more effective marginalizati...
15,27,1,0.458209,4_4_4,ODQA,"passages has the answer, the ques- tion will b..."
16,27,2,0.442168,5_5_4,RAG,the “closed-book” (parametric only) approaches...
17,27,3,0.434529,4_10_3,ODQA,TriviaQA: A large scale dis- tantly supervised...
18,27,4,0.417564,5_7_3,RAG,gold article is present in the top 10 retrieve...
19,27,5,0.406867,5_6_1,RAG,21.4 40.8 44.2 to more effective marginalizati...
20,28,1,0.394448,4_8_3,ODQA,tions where the retriever and reader are joint...
21,28,2,0.276753,3_14_0,NMT,Published as a conference paper at ICLR 2015 M...
22,28,3,0.270710,4_5_4,ODQA,DPR with BM25 in both single- and multi-datase...
23,28,4,0.258306,1_9_1,Attention,0.2 4.95 25.5 0.0 4.67 25.3 0.2 5.47 25.7 (E) ...
24,28,5,0.252562,4_8_1,ODQA,"model but pretrained on Wikipedia and CC-News,..."
25,29,1,0.397497,2_4_0,BERT,Model STS12 STS13 STS14 STS15 STS16 STSb SICK-...
26,29,2,0.382213,2_8_4,BERT,state-of-the-art sen- tence embeddings methods...
27,29,3,0.373671,2_7_0,BERT,Model MR CR SUBJ MPQA SST TREC MRPC Avg. Avg. ...
28,29,4,0.364623,2_5_0,BERT,sion method for the output. Model Spearman Not...
29,29,5,0.363510,2_2_3,BERT,BERT network structure is that no independent ...
30,30,1,0.278732,5_14_3,RAG,"social impacts of language models. ArXiv, abs/..."
31,30,2,0.258761,1_3_0,Attention,Figure 1: The Transformer - model architecture...
32,30,3,0.229076,1_8_1,Attention,is added to the sub-layer input and normalized...
33,30,4,0.227998,1_9_0,Attention,Table 3: Variations on the Transformer archite...
34,30,5,0.227613,5_11_0,RAG,[7] Christopher Clark and Matt Gardner. Simple...